<?php

namespace AppBundle\Repository;

/**
 * CrawlUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
