<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpellRepository extends EntityRepository
{
    /**
     * @param $characterClass
     *
     * @return array
     */
    public function findByCharacterClass($characterClass)
    {
        $qb = $this->createQueryBuilder('spells');

        $qb
            ->leftJoin('spells.characterClasses', 'cc')
            ->andWhere('cc.slug = :characterClass')
            ->setParameter('characterClass', $characterClass)
        ;

        return $qb->getQuery()->getResult();
    }
}
